# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/educations', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Education. As you add validations to Education, be sure to
  # adjust the attributes here as well.
  include TestAttributes
  include RequestHelpers

  let(:valid_education_attributes) do
    {
      educationName: 'Computer Science',
      educationType: 'major',
      educationDescription: 'Study of computers and computational systems'
    }
  end

  let(:invalid_education_attributes) do
    {
      educationName: nil, # Name can't be nil
      educationType: 'invalid_type', # Assuming 'type' has a validation for specific values
      educationDescription: '' # Assuming description can't be blank
    }
  end

  describe 'GET /index' do
    context 'when officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end

      it 'renders a successful response' do
        Education.create! valid_education_attributes
        get educations_url
        expect(response).to be_successful
      end
    end

    context 'when regular user is logged in' do
      let(:user) { User.create!(valid_attributes) }

      before do
        sign_in user
      end

      it 'redirects to root' do
        test_redirect_to_root(educations_url, nil)
      end
    end

    context 'when user is not logged in' do
      it 'redirects to signin' do
        test_redirect_to_signin(educations_url, nil)
      end
    end
  end

  describe 'GET /show' do
    context 'when officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it 'renders a successful response' do
        education = Education.create! valid_education_attributes
        get education_url(education)
        expect(response).to be_successful
      end
    end

    context 'when regular user is logged in' do
      let(:user) { User.create!(valid_attributes) }

      before do
        sign_in user
      end
      it 'redirects to root' do
        education = Education.create! valid_education_attributes
        test_redirect_to_root(education_url(education), nil)
      end
    end

    context 'when user is not logged in' do
      it 'redirects to signin' do
        education = Education.create! valid_education_attributes
        test_redirect_to_signin(education_url(education), nil)
      end
    end
  end

  describe 'GET /new' do
    context 'when officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it 'renders a successful response' do
        get new_education_url
        expect(response).to be_successful
      end
    end

    context 'when regular user is logged in' do
      let(:user) { User.create!(valid_attributes) }

      before do
        sign_in user
      end
      it 'redirects to root' do
        test_redirect_to_root(new_education_url, nil)
      end
    end

    context 'when user is not logged in' do
      it 'redirects to signin' do
        test_redirect_to_signin(new_education_url, nil)
      end
    end
  end

  describe 'GET /edit' do
    context 'when officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it 'renders a successful response' do
        education = Education.create! valid_education_attributes
        get edit_education_url(education)
        expect(response).to be_successful
      end
    end

    context 'when regular user is logged in' do
      let(:user) { User.create!(valid_attributes) }

      before do
        sign_in user
      end
      it 'redirects to root' do
        education = Education.create! valid_education_attributes
        test_redirect_to_root(edit_education_url(education), nil)
      end
    end

    context 'when user is not logged in' do
      it 'redirects to signin' do
        education = Education.create! valid_education_attributes
        test_redirect_to_signin(edit_education_url(education), nil)
      end
    end
  end

  describe 'POST /create' do
    
    context 'with valid parameters and officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it 'creates a new Education' do
        expect do
          post educations_url, params: { education: valid_education_attributes }
        end.to change(Education, :count).by(1)
      end

      it 'redirects to the created education' do
        post educations_url, params: { education: valid_education_attributes }
        expect(response).to redirect_to(education_url(Education.last))
      end
    end

    context 'with invalid parameters and officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it 'does not create a new Education' do
        expect do
          post educations_url, params: { education: invalid_education_attributes }
        end.to change(Education, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post educations_url, params: { education: invalid_education_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters and officer is logged in' do
      let(:new_attributes) do
        {
          educationName: 'Software Engineering',
          educationType: 'minor',
          educationDescription: 'Study of software development and engineering principles'
        }
      end

      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end

      it 'updates the requested education' do
        education = Education.create! valid_education_attributes
        patch education_url(education), params: { education: new_attributes }
        education.reload
        expect(education.educationName).to eq('Software Engineering')
        expect(education.educationType).to eq('minor')
        expect(education.educationDescription).to eq('Study of software development and engineering principles')
      end

      it 'redirects to the education' do
        education = Education.create! valid_education_attributes
        patch education_url(education), params: { education: new_attributes }
        education.reload
        expect(response).to redirect_to(education_url(education))
      end
    end

    context 'with invalid parameters but officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        education = Education.create! valid_education_attributes
        patch education_url(education), params: { education: invalid_education_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    context 'when officer is logged in' do
      let(:officer) { User.create!(valid_officer_attributes) }

      before do
        sign_in officer
      end

      it 'destroys the requested education' do
        education = Education.create! valid_education_attributes
        expect do
          delete education_url(education)
        end.to change(Education, :count).by(-1)
      end

      it 'redirects to the educations list' do
        education = Education.create! valid_education_attributes
        delete education_url(education)
        expect(response).to redirect_to(educations_url)
      end
    end
  end
end
